print("Welcome to the tip calculator\n")
bill = input("What is the total bill?")
tip = input("What percentage tip would you like to give? 10, 12, or 15?")
people = input("How many people to split the bill ?")
tip_total = float(bill) + ((float(bill) * float(tip))/100)
result = float(tip_total) / float(people)
final_amount = round(result, 2)
print(f"Each person should pay: {final_amount}")
